on:
  push:
    tags:
    - '*'
name: build-release
jobs:
  setup:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  windows:
    needs: setup
    name: windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: pyinstaller
        run: |
          pip install PyInstaller
          pip install requests
      - name: build
        run: pyinstaller jsn.py --onefile -i NONE --distpath build/dist/ --workpath build/work/
      - name: zip
        run: Compress-Archive -Path build/dist/* -DestinationPath build/Windows-x64.zip
      - name: upload
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./build/Windows-x64.zip
          asset_name: Windows-x64.zip
          asset_content_type: application/zip
  macos:
    needs: setup
    name: macos
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: pyinstaller
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
        run: |
          pip3 install PyInstaller
          pip3 install requests
      - name: build
        run: python3 -m PyInstaller jsn.py -y --onefile -i NONE --distpath build/dist/ --workpath build/work/
      - name: zip
        run: zip -rj build/macOS-x64.zip build/dist
      - name: upload
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./build/macOS-x64.zip
          asset_name: macOS-x64.zip
          asset_content_type: application/zip
  linux:
    needs: setup
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: pyinstaller
        run: |
          python3 -m pip install PyInstaller
          python3 -m pip install requests
      - name: build
        run: python3 -m PyInstaller jsn.py -y --onefile -i NONE --distpath build/dist/ --workpath build/work/
      - name: zip
        run: zip -rj build/linux-x64.zip build/dist
      - name: upload
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./build/linux-x64.zip
          asset_name: linux-x64.zip
          asset_content_type: application/zip